name: CI Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag Version'
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  release:
    runs-on: macos-latest

    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: Check out Git repository Fully
        uses: actions/checkout@v4
        if: github.event.inputs.tag_version != '' || github.ref_type == 'tag'
        with:
          fetch-depth: 0
          # lfs: true
      - name: Check out Git repository
        uses: actions/checkout@v4
        if: github.event.inputs.tag_version  == '' && github.ref_type != 'tag'
        with:
          fetch-depth: 1
          # lfs: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        shell: bash
        run: |
          xcodebuild -project 'ProcessReporter.xcodeproj' -scheme 'ProcessReporter' -configuration 'Release' -destination 'platform=macOS' build  -derivedDataPath 'build'

      - name: Create DMG
        shell: bash
        run: |
          hdiutil create -volname "ProcessReporter" -srcfolder "build/Build/Products/Release/ProcessReporter.app" -ov -format UDZO "ProcessReporter.dmg"

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ProcessReporter.dmg
          path: ProcessReporter.dmg
          retention-days: 90

      - name: Generate artifact attestation
        if: github.ref_type == 'tag' || github.event.inputs.tag_version != ''
        continue-on-error: true
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ProcessReporter.dmg

      - name: Upload DMG to GitHub Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ProcessReporter.dmg
          asset_name: ProcessReporter.dmg
          asset_content_type: application/x-apple-diskimage

      - run: npx changelogithub
        if: github.ref_type == 'tag' || github.event.inputs.tag_version != ''
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Version
        id: version
        uses: ./.github/actions/setup-version

      - name: Create Release Draft
        if: github.ref_type == 'tag' || github.event.inputs.tag_version != ''
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.version.outputs.APP_VERSION }}
          draft: false
          prerelease: true
          tag_name: v${{ steps.version.outputs.APP_VERSION }}
          files: ProcessReporter.dmg
